# fly.toml file generated for lpb-bun-hono on 2023-09-19T14:31:28+10:00

app = "lpb-bun-hono"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "syd"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
